import { ServicesService } from './index';
import { NotFoundException } from '@nestjs/common';
import { Service } from 'src/entities';

const UUID_REGEX =
  /^[0-9a-f]{8}-[0-9a-f]{4}-[1-5][0-9a-f]{3}-[89ab][0-9a-f]{3}-[0-9a-f]{12}$/i;

export async function syncSingleService(
  service: ServicesService,
  serviceId: string,
  targetAppInstanceId: string,
  syncOperationId: string,
  initiatedBy?: string,
): Promise<any> {
  // Get source service — first try DB lookup by real UUID.
  // Wrap in try-catch because PostgreSQL will throw if the ID is not a valid UUID format.
  let sourceService = null;
  try {
    sourceService = await service.serviceRepository.findOne({
      where: { id: serviceId },
      relations: [
        'appInstance',
        'appInstance.rancherSite',
        'appInstance.genericClusterSite',
        'appInstance.environment',
      ],
    });
  } catch (dbError) {
    service.logger.debug(
      `DB lookup failed for serviceId "${serviceId}" (likely a synthetic ID): ${dbError.message}`,
    );
  }

  // If not found (or DB threw for non-UUID format), check for synthetic ID format:
  // "${appInstanceId}-${serviceName}"
  // Synthetic IDs are generated by getServicesByAppInstanceDirect for the frontend.
  // Real UUIDs are exactly 36 chars; synthetic IDs are longer.
  if (!sourceService && serviceId.length > 36) {
    const possibleAppInstanceId = serviceId.substring(0, 36);
    const possibleServiceName = serviceId.substring(37); // skip the dash at position 36

    if (UUID_REGEX.test(possibleAppInstanceId) && possibleServiceName) {
      service.logger.debug(
        `Service not found by ID, trying synthetic ID fallback: appInstanceId=${possibleAppInstanceId}, serviceName=${possibleServiceName}`,
      );

      const sourceAppInstance = await service.appInstanceRepository.findOne({
        where: { id: possibleAppInstanceId },
        relations: ['rancherSite', 'genericClusterSite', 'environment'],
      });

      if (sourceAppInstance) {
        try {
          const adapter =
            await service.clusterAdapterFactory.createAdapter(sourceAppInstance);
          const deployments = await adapter.getDeployments(
            sourceAppInstance.cluster,
            sourceAppInstance.namespace,
          );
          const deployment = deployments.find(
            (d) => d.name === possibleServiceName,
          );

          if (deployment) {
            sourceService = new Service();
            sourceService.id = serviceId;
            sourceService.name = deployment.name;
            sourceService.appInstanceId = possibleAppInstanceId;
            sourceService.imageTag = deployment.image;
            sourceService.workloadType = deployment.type;
            sourceService.status = deployment.state;
            sourceService.replicas = deployment.scale;
            sourceService.availableReplicas = deployment.availableReplicas;
            sourceService.appInstance = sourceAppInstance;
          }
        } catch (fetchError) {
          service.logger.error(
            `Failed to fetch source service from cluster for synthetic ID ${serviceId}: ${fetchError.message}`,
          );
        }
      }
    }
  }

  if (!sourceService) {
    throw new NotFoundException(`Source service not found: ${serviceId}`);
  }

  // Get target app instance
  const targetAppInstance = await service.appInstanceRepository.findOne({
    where: { id: targetAppInstanceId },
    relations: ['rancherSite', 'genericClusterSite', 'environment'],
  });

  if (!targetAppInstance) {
    throw new NotFoundException(
      `Target app instance not found: ${targetAppInstanceId}`,
    );
  }

  // Find or create target service
  let targetService = await service.serviceRepository.findOne({
    where: { name: sourceService.name, appInstanceId: targetAppInstanceId },
  });

  const previousImageTag = targetService?.imageTag || '';

  service.logger.log(
    `Syncing service ${sourceService.name} from ${sourceService.appInstance.cluster}/${sourceService.appInstance.namespace} to ${targetAppInstance.cluster}/${targetAppInstance.namespace}`,
  );
  service.logger.log(`Source image: ${sourceService.imageTag}`);

  // Normalize workload type (remove plurals if present)
  const normalizedWorkloadType =
    sourceService.workloadType?.toLowerCase().replace(/s$/, '') || 'deployment';

  try {
    // Use adapter to update the workload
    const adapter =
      await service.clusterAdapterFactory.createAdapter(targetAppInstance);
    await adapter.updateWorkloadImage(
      targetAppInstance.cluster,
      targetAppInstance.namespace,
      sourceService.name,
      normalizedWorkloadType,
      sourceService.imageTag,
    );
    service.logger.log(
      `Successfully updated workload ${sourceService.name} in ${targetAppInstance.clusterType} cluster`,
    );
  } catch (clusterError) {
    service.logger.error(
      `Failed to update workload in cluster: ${clusterError.message}`,
    );
    throw new Error(`Cluster API update failed: ${clusterError.message}`);
  }

  // Update or create target service in database
  if (targetService) {
    targetService.imageTag = sourceService.imageTag;
    targetService.workloadType = normalizedWorkloadType;
    targetService.status = 'synced';
    targetService.lastSynced = new Date();
    targetService.updatedAt = new Date();
  } else {
    targetService = service.serviceRepository.create({
      name: sourceService.name,
      appInstanceId: targetAppInstanceId,
      status: 'synced',
      replicas: sourceService.replicas,
      availableReplicas: 0, // Will be updated on next fetch
      imageTag: sourceService.imageTag,
      workloadType: normalizedWorkloadType,
      lastSynced: new Date(),
    });
  }

  await service.serviceRepository.save(targetService);

  // Record sync in history with detailed information
  const startTime = Date.now();
  await service.syncHistoryRepository.save({
    syncOperationId,
    serviceId,
    serviceName: sourceService.name || null,
    workloadType: normalizedWorkloadType || null,
    sourceAppInstanceId: sourceService.appInstanceId,
    sourceEnvironmentName: sourceService.appInstance?.environment?.name || null,
    sourceCluster: sourceService.appInstance?.cluster || null,
    sourceNamespace: sourceService.appInstance?.namespace || null,
    targetAppInstanceId,
    targetEnvironmentName: targetAppInstance.environment?.name || null,
    targetCluster: targetAppInstance.cluster || null,
    targetNamespace: targetAppInstance.namespace || null,
    previousImageTag,
    newImageTag: sourceService.imageTag,
    containerName: sourceService.name || null,
    configChanges: {
      imageTag: {
        from: previousImageTag,
        to: sourceService.imageTag,
      },
    },
    status: 'success',
    durationMs: Date.now() - startTime,
    initiatedBy: initiatedBy || 'system',
    timestamp: new Date(),
  });

  return {
    serviceId,
    targetAppInstanceId,
    previousImageTag,
    newImageTag: sourceService.imageTag,
    status: 'success',
  };
}
